# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64076f24f18db5e04efef152a1e9e0187bde6ec1c5708eb94b1be79bdac438fb5ba4ca8d18cb833ac1902ca5b5b507d7bfeac85df8e424688e5cd65799111e2b

test:
  secret_key_base: d477e18ae9b11e4832ba4964663c521e640720ea1a312dfb26de5ffb39eddd73cd16e020c9200a358800ac7d44a32fc7bbe8d6131841b4112209498ea4f26551

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
